dist: focal
sudo: true
language: python

matrix:
  include:
  - python: 3.9
    name: "Py39-024+"
    env:
      - sklver=">=0.24.0"
      - jlver=">=1.0"
  - python: 3.8
    name: "Py38-023"
    env:
      - sklver="==0.23.2"
      - jlver="==0.17.0"

before_install:
    - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
    - wget https://apt.llvm.org/llvm.sh
    - chmod +x llvm.sh
    - sudo ./llvm.sh 10
    - ls /usr/bin/llvm*
    - export LLVM_CONFIG=/usr/bin/llvm-config
    # - sudo ln -s /usr/bin/llvm-config-10 /usr/bin/llvm-config
    - sudo apt-get -y install graphviz      

install:
  - pip install -r requirements.txt
  - pip install "scikit-learn$sklver"
  - pip install "joblib$jlver"

before_script:
  - python setup.py build_ext --inplace

script:
  - python setup.py unittests
