dist: focal
sudo: true
language: python
matrix:
  include:
  - python: 3.9
    name: "Py39"
install:
  - pip install -r requirements.txt
before_script:
  - python setup.py build_ext --inplace
script:
  - python setup.py unittests
