dist: xenial
sudo: true
language: python

python:
    - "3.7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install graphviz
install:
  - sudo apt-get install -qq gcc-6 g++-6
  - pip install pyquickhelper
  - pip install -r requirements_conda.txt
  - pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-win_amd64.whl
  - pip install -r requirements.txt
  - pip install cpyquickhelper
before_script:
  - python -u setup.py build_ext --inplace --verbose
script:
  - python setup.py unittests
