dist: bionic
sudo: true
language: python

matrix:
  include:
  - python: 3.7
    name: "Py37-skl022"
    env: sklearnc=">=0.22"
  - python: 3.8
    name: "Py38-skl022"
    env: sklearnc=">=0.22"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install graphviz
  - gcc --version
install:
  - pip install pyquickhelper cython scipy
  - pip install -r requirements.txt
  - pip install cpyquickhelper
  - pip install scikit-learn$sklearnc
  - python -c "import sklearn;print(sklearn.__version__)"
before_script:
  - python -u setup.py build_ext --inplace --verbose
script:
  - python setup.py unittests
