dist: xenial
sudo: true
language: python

python:
    - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install graphviz
install:
  - sudo apt-get install -qq gcc-6 g++-6
  - pip install -r requirements_conda.txt
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
  - pip install -r requirements.txt
  - pip install cpyquickhelper
before_script:
  - python setup.py build_ext --inplace
script:
  - python setup.py unittests
