dist: xenial
sudo: true
language: python

matrix:
  include:
  - python: 3.7
    name: "Py37-skl021"
    env: sklearnc=">=0.21"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install graphviz
install:
  - sudo apt-get install -qq gcc-6 g++-6
  - pip install pyquickhelper cython
  - pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-linux_x86_64.whl
  - pip3 install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp37-cp37m-linux_x86_64.whl
  - pip install -r requirements.txt
  - pip install cpyquickhelper
  - pip install scikit-learn$sklearnc
  - python -c "import sklearn;print(sklearn.__version__)"
before_script:
  - python -u setup.py build_ext --inplace --verbose
script:
  - python setup.py unittests
