dist: focal
sudo: true
language: python

matrix:
  include:
  - python: 3.10
    name: "Py310"
    env:
      - sklver=">=1.1"
      - jlver=">=1.0"

before_install:
    - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
    - sudo apt-get -y install graphviz      

install:
  - pip install pyquicksetup
  - pip install -r requirements.txt
  - pip install "scikit-learn$sklver"
  - pip install "joblib$jlver"

before_script:
  - python setup.py build_ext --inplace

script:
  - python setup.py unittests
