image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"
      SKL: '>=1.0'
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"
      SKL: '==0.24.2'
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  # for many packages
  - pip install llvmlite==0.38.0rc1 numba==0.55.0rc1
  - "%PYTHON%\\Scripts\\pip install -r requirements-win.txt"
  # install precompiled versions not available on pypi
  - "%PYTHON%\\Scripts\\pip install torch torchvision torchaudio"
  # other dependencies
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt --no-deps"
  - "%PYTHON%\\Scripts\\pip install scikit-learn%SKL%"
build: off

before_test:
  - "%PYTHON%\\python -u setup.py build_ext --inplace --verbose"

test_script:
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: mlinsights
