version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "requirements.txt" }}
          - v3-dependencies-

      - run:
          name: Install pandoc
          command: |
                    sudo apt-get update 
                    wget https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb
                    sudo dpkg -i pandoc-2.2.1-1-amd64.deb
          
      - run:
          name: Install tex
          command: |
                    sudo apt-get install -y texlive
                    sudo apt-get install -y texlive-latex-extra
                    sudo apt-get install -y dvipng
          
      - run:
          name: Install 7z, unrar
          command: |
                    sudo apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    sudo apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    sudo apt-get install -y graphviz
          
      # statsmodels setup.py requires it
      - run:
          name: install numpy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install numpy

      - run:
          name: Install cython
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install cython

      - run:
          name: Install pyproj (1)
          command: |
            sudo apt-get -qq update
            sudo apt-get install -y libproj-dev proj-bin proj-data

      - run:
          name: Install pyproj (2)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # pip install git+https://github.com/jswhit/pyproj.git
            pip install pyproj

      - run:
          name: Install pyproj (3) - optional
          command: |
            sudo apt-get install -y libc6
            sudo apt-get install libgeos-dev
            sudo apt-get install python-gdal gdal-bin
            wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj9_4.9.2-2_amd64.deb 
            sudo dpkg -i libproj9_4.9.2-2_amd64.deb 
            wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj-dev_4.9.2-2_amd64.deb
            sudo dpkg -i libproj-dev_4.9.2-2_amd64.deb

      - run:
          name: install dependencies (1)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_conda-3.7.txt

      - run:
          name: install dependencies (2)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: install cpyquickhelper>=0.1.187
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install cpyquickhelper>=0.1.187
            python -c "import cpyquickhelper.numbers;import cpyquickhelper;print(cpyquickhelper.__version__)"

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: compile and build
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py build_ext --inplace

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py unittests

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist
            mkdir -p test-reports/src
            cp -r  src/mlinsights test-reports/src

      - run:
          name: documentation
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py build_sphinx
            
      - run:
          name: copy documentation
          command: |
            mkdir -p test-reports/doc
            zip -r -9  test-reports/doc/documentation_html.zip _doc/sphinxdoc/build/html
            
      - store_artifacts:
          path: test-reports
          destination: test-reports